[toolchain]

[features]
seeds = false
skip-lint = false

# [programs.localnet]
# achievemint = "5SMBZMjXcW3r8tX25cMANwsSq5nFCBYAuFr8xNagDnA1"

[programs.devnet]
achievemint = "5SMBZMjXcW3r8tX25cMANwsSq5nFCBYAuFr8xNagDnA1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
